[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    login: Testes relacionados ao fluxo de autenticação
    carrinho: Testes relacionados ao carrinho de compras
    checkout: Testes relacionados ao fluxo de checkout e finalização de pedido

addopts = -v --tb=short
